#index:
#    path: /
#    controller: App\Controller\DefaultController::index
<<<<<<< HEAD
=======

app_logout:
    path: /logout

#easy_admin_bundle:
#    resource: '@EasyAdminBundle/Controller/EasyAdminController.php'
#    prefix: /admin
#    type: annotation
>>>>>>> b138e80aeb24d53e3e0a48ba34741c5b59ac0390
